channel: stable-4.10
version: 4.10.52
subscriptions:
  - name: rhacs-operator
    namespace: rhacs-operator
    channel: stable
    source: redhat-operators
  - name: openshift-pipelines-operator-rh
    namespace: openshift-operators
    channel: latest
    source: redhat-operators
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
acs:
  enabled: true
knative:
  enabled: false
kafka:
  enabled: false